# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Release
      run: |
        mkdir release
        git config --global user.email "hbattat@gmail.com" 
        git config --global user.name "hbattat"
        export REPOS=`curl -H "Authorization: token ${{secrets.ACTIONS_PAT}}" \
          "https://api.github.com/search/repositories?q=verifyemail-+in:name+user:hbattat+is:private" 2>/dev/null | \
          jq -r '.items | .[] | .name'`
        REPOS=`for i in $REPOS; do if [[ "$i" != "verifyemail-private" ]]; then echo -ne "$i "; fi; done;`
        for i in $REPOS; do \
          git clone https://hbattat:${{secrets.ACTIONS_PAT}}@github.com/hbattat/$i.git release/$i; \
          rsync -avr --exclude='release' --exclude='.git' --exclude='.github' . release/$i;
          changed_files=$(cd release/$i && git status --porcelain | wc -l)
          [ $changed_files -gt 0 ] && (cd release/$i && git add . && git commit -am "New update" && git push origin master)
        done;
